### ISSUE TITLE
AGit-flow 方式只有一条master分支，怎么做hotfix/ 版本修复

### ISSUE THREAD

**Issue by chenweiyj** [alibaba/git-repo-go#25]
AGit-flow 方式只有一条master分支，怎么做hotfix/ 版本修复。如果要hotfix修复，而master继续接收新功能的合并请求，hotfix修复好了怎么打hotfix的标签？

**Comment by jiangxin** [comment]
AGit-Flow 模式和分支开发模式当然可以共存。推送到 `refs/for/master/<topic>` 发起功能开发的评审，推送到 `refs/for/release/<topic>` 发起向 release 分支的代码评审，即 hotfix。多人协同的特性开发，仍然可以使用特性分支模式。如下图所示：

![image](https://user-images.githubusercontent.com/183860/110874390-a0790a80-830e-11eb-83f1-b6c19730108d.png)
