### ISSUE TITLE
维护问题

### ISSUE THREAD

**Issue by louis2610** [alibaba/git-repo-go#26]
像这种多仓库的项目是如何维护的？
分支如何划分？比如主仓库需要checkout一个新分支，子仓库的分支如何checkout？还有，清单仓库如何checkout?
还有，发布版本如何走流程？

**Comment by jiangxin** [comment]
`git-repo` 和 Android repo 兼容，可以查看 [git-repo 网站](https://git-repo.info)

1. 使用清单仓库中的 XML 文件定义项目地址和检出目录。
2. 清单仓库 checkout，使用 `git repo init -u <url>` 命令，完成清单仓库的克隆和检出。
3. 仓库无主仓库、子仓库的区分；检出分支使用 `git repo start --all <branch>` 即可在多个仓库检出同一个分支。
4. 版本发布，或者使用 `git repo manifest -r` 将项目的版本固定在当前提交上，或者在各个仓库中创建tag，然后修改 manifest 中的 XML 文件，设置项目版本为给定的 tag 名称。

**Comment by louis2610** [comment]
> `git-repo` 和 Android repo 兼容，可以查看 [git-repo 网站](https://git-repo.info)
> 
> 1. 使用清单仓库中的 XML 文件定义项目地址和检出目录。
> 2. 清单仓库 checkout，使用 `git repo init -u <url>` 命令，完成清单仓库的克隆和检出。
> 3. 仓库无主仓库、子仓库的区分；检出分支使用 `git repo start --all <branch>` 即可在多个仓库检出同一个分支。
> 4. 版本发布，或者使用 `git repo manifest -r` 将项目的版本固定在当前提交上，或者在各个仓库中创建tag，然后修改 manifest 中的 XML 文件，设置项目版本为给定的 tag 名称。

git repo manifest -r 这个是什么命令？有用法教程吗？

**Comment by jiangxin** [comment]
> git repo manifest -r 这个是什么命令？有用法教程吗？

很简单，一试便知
