### ISSUE TITLE
当manifest.xml文件中存在某个project的path字段没定义的情况下，会报错

### ISSUE THREAD

**Issue by zoujunhua** [alibaba/git-repo-go#27]
FATAL: duplicate path for project '.' in 'xxxxxxxxxxxx/.repo/manifest.xml'

当manifest.xml文件中存在某个project的path字段没定义的情况下，会报上面的错，

而谷歌的repo实现中，当遇到这种project时，path字段会默认赋值成name的相同值

**Comment by jiangxin** [comment]
Thank you for your report.  Will resolve this issue ASAP.

**Comment by jiangxin** [comment]
See pull request #29
