### ISSUE TITLE
What exactly does "diff driver" mean?

### ISSUE THREAD

**Issue by Cactusinhand** [alibaba/git-repo-go#28]
Hi @jiangxin 

As the title described, what does `diff dirver` mean in Git? 
It's the sum of all diff configuration variable like `diff.algorithm`, `diff.context`, `diff.external`, `diff.tool`, `diff.wordRegex` etc. ? 

Thanks!

**Comment by jiangxin** [comment]
A diff driver defines an external program which helps to generate diff output for a certain files.

BTW, this question has nothing to do with this project.

**Comment by Cactusinhand** [comment]
Sorry for bothering. I realized that this should be posted on your Gotgit project, but since it has been inactived for a long time, so I came here, seek for your reply 😃

**Comment by jiangxin** [comment]
> Sorry for bothering. I realized that this should be posted on your Gotgit project, but since it has been inactived for a long time, so I came here, seek for your reply 😃

We can discuss this question by email. You can find my email in log message in git project.
