### ISSUE TITLE
we use gitlab as git server？ what should we do on git server（gitlab） to support git-repo？

### ISSUE THREAD

**Issue by rhinoceros** [alibaba/git-repo-go#3]

**Comment by rhinoceros** [comment]
@jiangxin

**Comment by jiangxin** [comment]
Hi,

You can find detail in my blog:
* English version: https://git-repo.info/en/2020/03/agit-flow-and-git-repo/
* Chinese version: https://git-repo.info/zh_cn/2020/03/agit-flow-and-git-repo/

You can push Gitlab to implement this feature or implement it by yourself. To be brief:
1. Apply patches on Git from Git mailing list (https://public-inbox.org/git/20200518094039.757-1-worldhello.net@gmail.com/), or wait for next release of Git (10 weeks later).
2. Develop your own `proc-receive` hook for Git which will call merge-request API of Gitlab. You can take `t/helper/test-proc-receive.c` as an example.
3. Develop a new `ssh_info` API for gitlab, which advertises your service type.
4. Write an internal or external helper for `git-repo`.
