### ISSUE TITLE
git-pr命令已经被git-extras包含了，何解？

### ISSUE THREAD

**Issue by pixystone** [alibaba/git-repo-go#32]
```
$ g repo version
WARNING: you cannot use the git-repo alias command 'git-pr', it is overrided by '/usr/local/bin/git-pr' installed
git-repo version 0.7.7
git version 2.25.0
```

![image](https://user-images.githubusercontent.com/3050696/131302301-ab9391e2-b598-4718-aaa5-c76c366da392.png)

**Comment by jiangxin** [comment]
git-repo 的配置文件安装在：`~/.git-repo/gitconfig`。这个配置文件中针对创建代码评审创建了好几个别名命令：

- git pr
- git peer-review
- git review

大概率可以使用 `git peer-review`。您也可以自己定义笔名命令：

```
git config --global alias.<别名> "repo upload --single"
```
