### ISSUE TITLE
remote 'origin' for project is not reviewable while executing command "git pr"

### ISSUE THREAD

**Issue by robertzhangwenjie** [alibaba/git-repo-go#33]
➜  InterfaceTestingFramework git:(master) git pr
Error: remote 'origin' for project 'InterfaceTestingFramework' is not reviewable

**Comment by jiangxin** [comment]
Please report with detail informations:

1. Versions of git and git-repo.
2. What is the URL of remote "origin"?  Show it using "git remote get-url origin"
3. Turn on verbose output by running "git pr -vv"

**Comment by xlmeng1988** [comment]
I got he following verbose output:
> $ git pr -vv
DEBUG: get ssh_info from command: ssh gitlab@gitlab.xxx.com ssh_info
DEBUG: fail to check ssh_info for SSH protocol, will check HTTP instead
DEBUG: get ssh_info from API: https://gitlab.xxx.com/ssh_info
DEBUG: fail to get proxy from git config: http.proxy is not set
DEBUG: get ssh_info from API: http://gitlab.xxx.com/ssh_info
DEBUG: 404: bad ssh_info response of 'http://gitlab.xxx.com/ssh_info'
Error: remote 'origin' for project 'test' is not reviewable

**Comment by jiangxin** [comment]
Only a few servers including devops.aliyun.com are supported. The servers must implement :
* a "proc-receive" hook, which was first introduced to git v2.29.0 by us. See: https://github.com/git/git/blob/v2.29.0/Documentation/githooks.txt#L339-L398
* a URL which provide version of the protocol, like: https://codeup.aliyun.com/ssh_info

**Comment by mxplusb** [comment]
go-gitea/gitea#27014 and go-gitea/gitea#27021 will formally enable this for Gitea, but it has been supported since 1.13.
