### ISSUE TITLE
How to submit 'git pr' without opening an editor?

### ISSUE THREAD

**Issue by Ncerzzk** [alibaba/git-repo-go#34]
version info:
git-repo version 0.7.6
git version 2.19.1.6.gb485710b

I have some regression tests which would update the code, and it's a bit dangerous to git push directly.
Is there a way to submit 'git pr' without opening an editor?

I tried `gir pr --no-edit -y`, but still opened the editor.

**Comment by jiangxin** [comment]
> version info: git-repo version 0.7.6 git version 2.19.1.6.gb485710b
> 
> I have some regression tests which would update the code, and it's a bit dangerous to git push directly. Is there a way to submit 'git pr' without opening an editor?
> 
> I tried `gir pr --no-edit -y`, but still opened the editor.

There is no such option `-y`:

```
$ git-repo upload --single --no-edit -y
Error: unknown shorthand flag: 'y' in -y
```

There is a hidden option `--assume-yes`, you can try:

```
$ git pr --no-edit --assume-yes
```

`git pr` is an alias command, show me the hidden options of `git pr`:

```
$ git config alias.pr  
repo upload --single
```

**Comment by Ncerzzk** [comment]
Thank you, this is what i want.
