### ISSUE TITLE
不兼容m1 pro 吗？

### ISSUE THREAD

**Issue by LevineHua** [alibaba/git-repo-go#39]

**Comment by jiangxin** [comment]
陈博俊（@Berger7）贡献了 macOS arm64 编译和下载的代码，测试通过后会发布对应版本。参见：

+ https://github.com/alibaba/git-repo-go/pull/36

**Comment by jiangxin** [comment]
You can download arm64 version for Apple M1 chips [git-repo-0.7.8-macOS-arm64.tar.gz](https://github.com/alibaba/git-repo-go/releases/download/v0.7.8/git-repo-0.7.8-macOS-arm64.tar.gz)
