### ISSUE TITLE
git pr can not deal with shell variable expansion correctly

### ISSUE THREAD

**Issue by xiejingf** [alibaba/git-repo-go#45]
git pr will truncate the shell variable if the variable contains whitespace characters.
![1](https://user-images.githubusercontent.com/17525081/145157387-104fadbd-4db8-4a2e-847a-6c55b3f14aea.png)

![2](https://user-images.githubusercontent.com/17525081/145157544-1989344e-62f6-4399-89a9-8daa04fb390d.png)

I have double checked the value expansion expression, it seems correct, so there must be something wrong during the processing of git pr
![3](https://user-images.githubusercontent.com/17525081/145157785-4795671b-91ec-4d36-acf7-6b9f76042880.png)

**Comment by jiangxin** [comment]
I am sure that the whole one line title can be sent to git using push-options, see test case:

    https://github.com/alibaba/git-repo-go/blob/master/test/t0400-upload-basic.sh#L277

Please check the code of "proc-receive" hook.  May be only part of the title is sent to merge-request API.

**Comment by jiangxin** [comment]
It's wrong to add backslash before double quote characters. Please use `--title "..."` instead of `--tiltle \"...\"`.

**Comment by xiejingf** [comment]
after some tests,  I finally get it work. My script use expect programe to spawn a process

the code below does not work as expected
```
/usr/bin/expect <<-EOF
	set time 10
	spawn git pr --no-edit --reviewers $REVER --title "$DESC"
	expect {
	"*(y/N)?" { send "y\r"; exp_continue }
	"*did you forget to amend?)" { send "y\r" }
	}
```
use curly brackets (```{}```) to make the content inside ```{}``` passed as a whole
```
/usr/bin/expect <<-EOF
	set time 10
	spawn git pr --no-edit --reviewers $REVER --title {$DESC}
	expect {
	"*(y/N)?" { send "y\r"; exp_continue }
	"*did you forget to amend?)" { send "y\r" }
	}
```

similar issue in stackoverflow : https://stackoverflow.com/questions/12518354/use-expect-to-spawn-command-with-arguments-containing-spaces
