### ISSUE TITLE
不兼容google 的 repo工具格式，所以下载谷歌的开源代码是下载不下来

### ISSUE THREAD

**Issue by cnmade** [alibaba/git-repo-go#48]
https://chromium.googlesource.com/chromiumos/

试了一下谷歌的开源项目，用谷歌的repo工具，没问题，可以正常下载。
用阿里的，就不行。。。

本来还以为可以替代掉谷歌的工具，结果发现想多了。。。

还是只能用谷歌的标准，谷歌的工具。

**Comment by jiangxin** [comment]
抱歉，和 gerrit 兼容性还缺乏验证。工具的用户群体尚未触及 gerrit，需要贡献者。
