### ISSUE TITLE
git repo upload 404?

### ISSUE THREAD

**Issue by jinri** [alibaba/git-repo-go#55]
git repo upload
WARNING: You are suggested to install or upgrade git to version 2.10.0 or above
        * The git-interpret-trailers command introduced in git 2.2.0 is used for the Gerrit commit-msg hook.
        * sending custom HTTP headers is only supported in git 2.9.0 and above
        * Some review options are sent using git push-options which are available in git 2.10.0 and above.
ERROR: 404: bad ssh_info response of 'https://xxxx/ssh_info'
Error: fail to load remotes: origin

**Comment by jiangxin** [comment]
Please use `git repo upload -vv` to show more log message.  The URL "http://host-name/ssh_info" is used to tell the protocol the server supports.

**Comment by jiangxin** [comment]
Only a few servers including devops.aliyun.com are supported. The servers must implement :

* a "proc-receive" hook, which was first introduced to git v2.29.0 by us. See: https://github.com/git/git/blob/v2.29.0/Documentation/githooks.txt#L339-L398
* a URL which provide version of the protocol, like: https://codeup.aliyun.com/ssh_info
