### ISSUE TITLE
打开推送评审模式后应该如何推送PR

### ISSUE THREAD

**Issue by kennir** [alibaba/git-repo-go#58]
git repo upload 是否可以兼容 codeup 的推送凭审模式吗? 还是需要用 foreach 去 push 每个库?

谢谢

**Comment by xzy57369** [comment]
codeup上开启推送评审后，使用 git push 就可以自动创建评审，不依赖git-repo

**Comment by jiangxin** [comment]
codeup 即阿里云·云效代码平台，同时支持 Gerrit 模式和推送评审模式。

* Gerrit 模式就是使用特殊的 `git push` 命令行推送到特殊引用 `refs/for/<branch>/<topic>`。
* 推送评审模式是对 Gerrit 模式的一种简化，可以直接推送到分支，如 `git push` 即可创建代码评审。

如果在云效 codeup 上操作多仓库，建议任然使用 git-repo 默认的 Gerrit 模式。这是因为 Gerrit 模式的特殊引用 `refs/for/<branch>/<local-branch>` 可以提供 `<local-branch>` 信息，这样服务端能够识别推送操作是创建新的代码评审，还是更新老的代码评审。而推送评审模式在推送时没有相关信息，服务端难以识别用户的 push 操作应该创建新的代码评审，还是更新老的代码评审，可能需要客户端提供 `-o review=<argument>` 参数，这给多仓库的 git-repo 工具带来编程难度。

**Comment by kennir** [comment]
知晓了, 谢谢楼上的答复
