### ISSUE TITLE
支持的GIT仓库列表说明

### ISSUE THREAD

**Issue by airclear** [alibaba/git-repo-go#7]
建议列举支持的GIT仓库清单。

只在codeup的文档里看到说：

```
git-repo 可以支持 AGit-Flow 兼容的代码平台以及 Gerrit。
```

具体的有哪些？github、gitlab、gitee这些能支持吗？

**Comment by jiangxin** [comment]
AGit-Flow 涉及对 Git 核心的更改，补丁已经演进到第 19 版本： https://public-inbox.org/git/20200827154551.5966-1-worldhello.net@gmail.com/ 。目前这个特性在 Git 的 seen 分支，尚未合入 next 或者 master 分支。等到这个特性随 Git 发布，GitHub 或者与其类似的平台才有可能添加支持。

**Comment by samkahchiin** [comment]
@jiangxin 请问现在支持github了吗？

**Comment by jiangxin** [comment]
AGit-Flow 在 Git 核心引入两个特性，一个是 proc-receive 钩子，一个是 report-status-v2，都已经合入到 Git v2.29.0 版本中了。 GitHub 应该还没有支持这个特性，再和 Peff (Jeff King) 的讨论中可以看出 GitHub 为了实现分布式架构，对 git-receive-pack 做了大量修改，这个特性不会直接引入。
